server:
  port: 8088

spring:
  datasource:
    url: jdbc:sqlserver://192.168.121.21:1433;database=KRON_DEV;encrypt=false;trustServerCertificate=true
    username: KalimullinIR
    password: Ilyas%2024%
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
